### ISSUE TITLE
Interjecting questions?

### ISSUE THREAD

**Issue by NilesDev** [HeMan/jobbergate#26]
Using the standard way to add questions (appform.List etc) appends it to the list of questions. Is there a way to add it to the front of the deque instead, to be asked immediately? 

e.g. "running or finished job dependency?": depending on the answer, you need to ask for either job ID or a .res file in the current folder. You want to ask this followup in connection to the first question, not a few questions later.

Another possibility is to front load all possible questions, and remove them from the queue as they become irrelevant, but it seems messy.

**Comment by HeMan** [comment]
The problem is that the web-part can't add extra questions in any simple way since it's forms-based.

**Comment by HeMan** [comment]
Some workflows could need follow up questions, but since we only have one level of flows this can't be achieved now.

**Comment by HeMan** [comment]
ff0e0956c4e6a7e902c37ff1af4d97b5b7761377 should solve this. @NilesDev  could you try?
