### ISSUE TITLE
Import answer to questions from file

### ISSUE THREAD

**Issue by niklasmelin** [HeMan/jobbergate#28]
Why:
Allow for batch submission of multiple jobs or re-submission of a similar job.

How:
The questions answered through the questionnaire should be populated to avoid user interaction.

Expected result:
A job-file containing the same information as if the job was submitted manually.

**Comment by HeMan** [comment]
Should the questions that is answered still be shown or should only questions without answers be shown?

**Comment by niklasmelin** [comment]
As the goal is automation in batch, I would prefer an error rather than popping up questions which halt program execution if required variables are missing or generate an exception by missing files etc.

**Comment by HeMan** [comment]
Could there be a case when all but one question (for example input file name) is pre-aswered and the user only answers that? Or is the usecase to build answer-files that populates the template without any interaction?

**Comment by niklasmelin** [comment]
Yes this is also a viable use case. Can both use cases coexist?

**Comment by HeMan** [comment]
Yes, but if only the one with fully populated answers should be used I'd do a simpler approach in my code.

**Comment by niklasmelin** [comment]
Then I suggest that we start off with the simple solution.

**Comment by HeMan** [comment]
Fixed it. Please try if it works as expected.

**Comment by HeMan** [comment]
Oh! Forgot to discuss if web also needs this functionality? Is it really feasible?

**Comment by niklasmelin** [comment]
I don´t think its relevant for the web application.

**Comment by HeMan** [comment]
Great. I'll close this ticket.
