### ISSUE TITLE
Apps not found if app not launched from jobbergate

### ISSUE THREAD

**Issue by niklasmelin** [HeMan/jobbergate#41]
The jobbergate.yaml file is not found by the framework if the app is launched in an other folder. Should the yaml-file be installed so that it is found globally?

**Comment by HeMan** [comment]
I think we should rather have an environment variable pointing out the config, an argument to flask and perhaps a default location for the file. What do you think, should I implement environment variable and flask argument?

**Comment by niklasmelin** [comment]
The end user should not have to know how anything is installed. A potential problem is if the user has to add something to the .bashrc or etc. to expose the variable as they don´t know how to do this...

Hence I promote a from a user perspective trivial solution where "someone" set up the flask application and the end user may consume by issuing a simple command such as "abaqus-jobbers" in the terminal. Loading a module "abaqus" prior is also an acceptable solution.

**Comment by HeMan** [comment]
Resolvet by #44
